package com.google.android.gms.common.api.internal;

import androidx.annotation.C0193h0;
import androidx.annotation.C0195i0;
import com.google.android.gms.common.api.C4237l;
import com.google.android.gms.common.api.C4237l.C4238a;
import com.google.android.gms.common.api.C4246q;
import com.google.android.gms.common.api.C4247r;
import com.google.android.gms.common.api.C4249t;
import com.google.android.gms.common.api.C4250u;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.internal.C4300a0;
import com.google.android.gms.common.internal.C4312d0;
import java.util.concurrent.TimeUnit;

/* renamed from: com.google.android.gms.common.api.internal.h2 */
/* compiled from: com.google.android.gms:play-services-base@@17.1.0 */
public final class C4135h2<R extends C4246q> extends C4237l<R> {

    /* renamed from: a */
    private final Status f12950a;

    public C4135h2(Status status) {
        C4300a0.m18621a(status, (Object) "Status must not be null");
        C4300a0.m18628a(!status.mo17617T(), (Object) "Status must not be success");
        this.f12950a = status;
    }

    @C0193h0
    /* renamed from: a */
    public final R mo17739a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final void mo17653b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public final boolean mo17749c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @C0195i0
    /* renamed from: d */
    public final Integer mo17750d() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* access modifiers changed from: 0000 */
    @C0193h0
    /* renamed from: e */
    public final Status mo17842e() {
        return this.f12950a;
    }

    @C0193h0
    /* renamed from: a */
    public final R mo17740a(long j, @C0193h0 TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo17745a(@C0193h0 C4247r<? super R> rVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo17746a(@C0193h0 C4247r<? super R> rVar, long j, @C0193h0 TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo17743a(@C0193h0 C4238a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @C0193h0
    @C4312d0
    /* renamed from: a */
    public final <S extends C4246q> C4250u<S> mo17741a(@C0193h0 C4249t<? super R, ? extends S> tVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
